ask/ask/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^', include('qa.urls')),
]

ask/qa/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.auth.views import password_change

app_name = "qa"
urlpatterns = [
    # url(r'^login/', views.user_login, {'template_name': 'login.html'}, name='user_login'),
    # url(r'^accounts/profile/', password_change, name='password_change'),
    url(r'^$', views.home, name='home'),
    url(r'^login/', views.login, name='login'),
    url(r'^accounts/login/', views.login, name='login'),
    url(r'signup/', views.signup, name='signup'),
    url(r'logout/', views.logout, name='logout'),
    url(r'question/(?P<qid>\d+)/', views.question_detail, name='question_details'),
    url(r'ask/', views.add_question, name='add_question'),
    url(r'popular/', views.popular_questions, name='popular_questions'),
    url(r'new/', views.new_questions, name='new_questions')
]

ask/qa/forms.py
from django import forms
from django.shortcuts import get_object_or_404
# from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.db.utils import IntegrityError
from . import models


class RatingForm(forms.Form):
    CHOICES = ((1, "Очень плохо"), (2, "Плохо"), (3, "Нормально"), (4, "Хорошо"), (5, "Отлично"))
    rating = forms.ChoiceField(choices=CHOICES)

    def __init__(self, user, qid, *args, **kwargs):
        self._user = user
        self._qid = qid
        super(RatingForm, self).__init__(*args, **kwargs)

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        return rating

    def save(self):
        question = get_object_or_404(models.Question, id=self._qid)
        rating = question.objects.set(rating=self.cleaned_data['rating'])
        question.save()
        return rating


class AskForm(forms.Form):
    title = forms.CharField(max_length=100, label="Заголовок вопроса")
    text = forms.CharField(widget=forms.Textarea, label="Вопрос")

    def __init__(self, user, *args, **kwargs):
        self._user = user
        super(AskForm, self).__init__(*args, **kwargs)

    def clean_title(self):
        print(self.cleaned_data['title'])
        title = self.cleaned_data['title']
        return title

    def clean_text(self):
        print(self.cleaned_data['text'])
        text = self.cleaned_data['text']
        return text

    def save(self):
        print("Save:", self.cleaned_data)
        question = models.Question(**self.cleaned_data)
        # question.author, _ = models.User.objects.get_or_create(username='anon')
        question.author = self._user
        question.save()
        return question


class AnswerForm(forms.Form):
    # question = forms.ModelChoiceField(required=True, queryset=None, widget=forms.HiddenInput)
    # question = forms.IntegerField(required=False, widget=forms.HiddenInput, label="QID")
    text = forms.CharField(widget=forms.Textarea, label="Комментарий")

    def __init__(self, user, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self._qid = kwargs.get('initial', None)
        self._user = user

        if self._qid is not None:
            self._qid = self._qid.get('qid', None)

        print("__init__", "self._qid:", self._qid, "args:", args, "kwargs", kwargs)

    def clean_question(self):
        print(self.cleaned_data['question'])
        question = self.cleaned_data['question']
        return question

    def clean_text(self):
        print(self.cleaned_data['text'])
        text = self.cleaned_data['text']
        return text

    def save(self):
        self.cleaned_data['question'] = self._qid
        self.cleaned_data['author'] = self._user
        answer = models.Answer(**self.cleaned_data)
        answer.save()
        print("save:", self)
        return answer


class CreateUserForm(forms.Form):
    username = forms.CharField(max_length=50, required=False)
    email = forms.CharField(widget=forms.EmailInput, required=False)
    password = forms.CharField(widget=forms.PasswordInput, required=False)

    # def clean_username(self):
    #     print("clean_username:", self.cleaned_data['username'])
    #     username = self.cleaned_data['username']
    #     return username
    #
    # def clean_email(self):
    #     print("clean_email:", self.cleaned_data['email'])
    #     email = self.cleaned_data['email']
    #     return email
    #
    # def clean_password(self):
    #     print("clean_password:", self.cleaned_data['password'])
    #     password = self.cleaned_data['password']
    #     return password

    def save(self):
        print("self.cleaned_data:", self.cleaned_data)
        try:
            user = models.User.objects.create_user(username=self.cleaned_data['username'],
                    email=self.cleaned_data['email'], password=self.cleaned_data['password'])
        except IntegrityError:
            print("User exists:", self.cleaned_data['username'])
            user = None
        return user

class AuthUserForm(forms.Form):
    username = forms.CharField(max_length=50)
    password = forms.CharField(widget=forms.PasswordInput)

ask/qa/old/forms.py
from django import forms
from . import models

class AskForm(forms.Form):
    title = forms.CharField(max_length=100)
    text = forms.CharField(widget=forms.Textarea)

    # def __init__(self, user, **kwargs):
    #     self._user = user
    #     super(AskForm, self).__init__(**kwargs)

    # def clean(self):
    #     if self._user.is_banned:
    #         raise forms.ValidationError("Access denied")

    def clean_text(self):
        text = self.cleaned_data['text']
        # if not is_ethic(text):
        #     raise forms.ValidationError("Сообщение не корректно", code=12)
        return text

    def save(self):
        # self.cleaned_data['author'] = self._user
        question = models.Question(**self.cleaned_data)
        question.save()
        return question


class AnswerForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea)
    question = forms.ModelChoiceField(required=True, queryset=None)

    def __init__(self, queryset, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.fields['question'].queryset = models.Answer.objects.filter(question=kwargs['qid'])
        #self.fields['question'].qid = kwargs['initial']['qid']
        #print("self.fields['question'].qid:", self.fields['question'].qid)
        # print("self.fields['question']", self.fields['question'])

    # def clean_quiestion(self):
    #     print("clean_question:", self.cleaned_data['question'].qid)
    #     question = self.cleaned_data['question'].qid
    #     return question


    def clean(self):
        # if is_spam(self.clean_data):
        #     raise forms.ValidationError("Сообщение похоже на спам!", code="spam")
        pass


# class AnswerForm(forms.Form):
#     text = forms.CharField(widget=forms.Textarea)
#     question = forms.ModelChoiceField(required=True, queryset=None)
#
#     def __init__(self, *args, **kwargs):
#         super(AnswerForm, self).__init__(*args, **kwargs)
#         #super(AnswerForm, self).__init__()
#         self.fields['question'].queryset = args
#
#     def clean(self):
#         pass

ask/qa/old/views.py
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.http import require_GET
from django.core.paginator import Paginator, EmptyPage
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from . import models
from . import forms

def paginate(request, queryset):
    try:
        limit = int(request.GET.get('limit', 10))
    except ValueError:
        limit = 10

    if limit > 100 or limit < 1:
        limit = 10

    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        raise Http404

    paginator = Paginator(queryset, limit)

    try:
        page = paginator.page(page)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    return paginator, page

# def login(request):
#     error = ""
#     if request.method == "POST":
#         login = request.POST.get('login')
#         password = request.POST.get('password')
#         url = request.POST.get('continue', '/')
#         sessid = models.do_login(login, password)
#         if sessid:
#             response = HttpResponseRedirect(url)
#             response.set_cookie('sessid', sessid, domain='', httponly=True,
#                                 expires=datetime.now()+timedelta(days=5)
#                                 )
#             return response
#         else:
#             error = "Неверный логин или пароль"
#     return render(request, "login.html", {
#         'error': error
#     })


def home(request):
    return questions_list_on_page(request)

def questions_list_on_page(request, questions_queryset=models.Question.objects.order_by('id'),
                           template="questions_main.html"):
    """Функция принимает отсортированный queryset (если не указан, тогда сортирует по id),
    а затем разбивает его на страницы используя произвольные шаблоны"""

    paginator, page = paginate(request, questions_queryset)
    # paginator.baseurl = reverse(reverse_url)
    return render(request, template, {
        'questions_on_page': page.object_list,
        'paginator': paginator,
        'page': page
    })

def add_question(request):
    if request.method == "POST":
        form = forms.AskForm(request.POST)
        if form.is_valid():
            post = form.save()
            url = post.get_url()
            return HttpResponseRedirect(url)
    else:
        form = forms.AskForm()
    return render(request, "question_add.html", {
        'form': form
    })

def login(request):
    return HttpResponse(request)

def signup(request):
    return HttpResponse(request)

@require_GET
def question_detail(request, qid):
    question = get_object_or_404(models.Question, id=qid)
    answers = models.Answer.objects.filter(question=qid)
    # answers = models.Answer.question_set.all()
    # likes = question.likes.all()

    return render(request, "question_details.html", {
        'question': question,
        'answers': answers,
    })

#@login_required
def add_question(request):
    if request.method == "POST":
        # form = forms.AskForm(request.user, request.POST)
        form = forms.AskForm(request.POST)
        if form.is_valid():
            question = form.save()
            url = question.get_url()
            return HttpResponseRedirect(url)
    else:
        form = forms.AskForm()
    return render(request, "question_add.html", {
        'form': form
    })

def popular_questions(request):
    questions = models.Question.objects.popular()
    return questions_list_on_page(request, questions, "questions_popular.html")

def new_questions(request):
    questions = models.Question.objects.new()
    return questions_list_on_page(request, questions, "questions_new.html")

ask/qa/views.py
# from django.views.decorators.http import require_GET
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage
from django.contrib.auth import views, authenticate, login as django_login, logout as django_logout
from django.views import generic

from . import models
from . import forms


def paginate(request, queryset):
    """Функция будет разбивать queryset на несколько страниц, если превышен заданный лимит на количество записей.
    Возвращает объект пагинатор и текущую страницу. Если страница указана не верно, вернет последнию страницу."""

    try:
        limit = int(request.GET.get('limit', 10))
    except ValueError:
        limit = 10

    if limit > 100 or limit < 1:
        limit = 10

    try:
        page = int(request.GET.get('page', 1))
    except ValueError:
        raise Http404

    paginator = Paginator(queryset, limit)

    try:
        page = paginator.page(page)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)

    return paginator, page


def home(request):
    return questions_list_on_page(request)


def questions_list_on_page(request, questions_queryset=models.Question.objects.order_by('id'),
                           template="qa/questions_main.html"):
    """Функция принимает отсортированный queryset (если не указан, тогда сортирует по id),
    вызывает функцию paginate, разбивает вопросы на страницы и возвращает html текст
    используя переданный шаблон."""

    paginator, page = paginate(request, questions_queryset)
    return render(request, template, {
        'questions_on_page': page.object_list,
        'paginator': paginator,
        'page': page,
        'user': request.user,
    })


def change_password(request):
    template_response = views.password_change(request)
    # Do something with `template_response`
    return template_response


def logout(request):
    django_logout(request)
    return HttpResponseRedirect("/")


def login(request):
    if request.method == "POST":
        form = forms.AuthUserForm(request.POST)
        if form.is_valid():
            username = request.POST.get('username', None)
            password = request.POST.get('password', None)
            # url = request.POST.get('continue', '/')
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    django_login(request, user)
                    return HttpResponseRedirect("/")
                else:
                    return HttpResponse("Account disabled")
            else:
                return render(request, "qa/user_login.html", {
                    'form': form,
                    'error': True
                })
    else:
        form = forms.AuthUserForm()

    return render(request, "qa/user_login.html", {
        'form': form,
        'error': None
        })


def signup(request):
    if request.method == "POST":
        print("Request POST:", request.POST)
        form = forms.CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            if user:
                return login(request)
                # return HttpResponseRedirect("/")
            else:
                return render(request, "qa/user_new.html", {
                    'form': form,
                    'errors': ["User wasn't created"],
                })
    else:
        form = forms.CreateUserForm()
    return render(request, "qa/user_new.html", {
        'form': form,
        'errors': form.errors,
        })


@login_required
def add_question(request):
    if request.method == "POST":
        # form = forms.AskForm(request.user, request.POST)
        form = forms.AskForm(request.user, request.POST)
        if form.is_valid():
            question = form.save()
            url = question.get_url()
            return HttpResponseRedirect(url)
    else:
        form = forms.AskForm(request.user)

    return render(request, "qa/question_add.html", {
        'form': form
    })


def question_detail(request, qid):
    question = get_object_or_404(models.Question, id=qid)
    answers = models.Answer.objects.filter(question=qid)
    if request.method == "POST" and request.user.is_authenticated():
        form = forms.AnswerForm(request.user, request.POST, initial={'qid': question})
        if form.is_valid():
            answer = form.save()
            url = answer.get_url()
            return HttpResponseRedirect(url)
        else:
            print("form.is_valid = FALSE")
    else:
        form = forms.AnswerForm(request.user)

    return render(request, "qa/question_details.html", {
        'question': question,
        'answers': answers,
        'form': form,
    })

def question_rating(request, qid):
    # question = get_object_or_404(models.Question, id=qid)
    if request.method == "POST" and request.user.is_authenticated():
        form = forms.RatingForm(request.user, qid, request.post)
        if form.is_valid():
            rating = form.save()
            url = rating.get_url()
            return HttpResponseRedirect(url)
        else:
            print("form.is_valid = FALSE")
    else:
        form = forms.AnswerForm(request.user, qid)

    return render(request, ".html", {
        'xz': "xz"
    })

def popular_questions(request):
    questions = models.Question.objects.popular()
    return questions_list_on_page(request, questions, "qa/questions_popular.html")


def new_questions(request):
    questions = models.Question.objects.new()
    return questions_list_on_page(request, questions, "qa/questions_new.html")


def comments_list(request):
    qid = request.Get.get('qid')
    question = get_object_or_404(models.Question, qid)
    comments = paginate(request, question.question)
    return render(request, "qa/comments.html", {
        'comments': comments
    })


# def allow_cors(origin_view):
#     def new_view(request, *args, **kwargs):
#         response = origin_view(request, *args, **kwargs)
#         origin = request.META.get('HTTP_ORIGIN')
#         if not origin:
#             return response
#         for domain in settings.CORS_WHITE_LIST:
#             if origin.endswith('.' + domain):
#                 response['Access-Control-Allow-Origin'] = origin
#         return response
#     return new_view

ask/qa/templates/qa/base.html
<!DOCTYPE html>
<html lang="ru" xmlns="http://www.w3.org/1999/html">

    {% load staticfiles %}

    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'qa/styles.css' %}">
        <meta charset="UTF-8">

        <title>{% block title %}Q&A{% endblock %}</title>
        {% block extrahead %}{% endblock %}
    </head>

    <body>
        <div>
            <h1><a href="/">Вопросы и ответы</a></h1>
        </div>

        <div class="user-info">
            {% if user.is_authenticated %}
                <p>Welcome, {{ user.username }}. <a href="{% url 'qa:logout' %}">Logout</a></p>
            {% else %}
                <p>Welcome, new user. <br>Please <a href="{% url 'qa:login' %}">log in</a> or
                    <a href="{% url 'qa:signup' %}">create new account</a></p>
            {% endif %}
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>

    </body>
</html>

ask/qa/templates/qa/login.html
{% extends "qa/base.html" %}

{% block content %}

{% if error %}
    <div class="alert alert-danger">
        <font color="red">Your username and password didn't match. Please try again.</font>
    </div>
{% endif %}

<form method="post" action="{% url 'qa:login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

ask/qa/templates/qa/main_page.html
{% extends "qa/base.html" %}

{% block title %}
    {{ block.super }} - главная
{% endblock %}

{% block content %}

    {% for question in question_list %}
    <div class="question">
        {# <a href="{{ question.build_url }}">{{ question }}</a> #}
        <a href="{% url 'qa:question_details' question.id %}">{{ question }}</a>
        {{ question.create_date|date:"d.m.y" }}
    </div>
    {% endfor %}

{% endblock %}

ask/qa/templates/qa/question_add.html
{% extends "qa/base.html" %}

{% block title %}
    {{ block.super }} - Спросить
{% endblock %}

{% block content %}

{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}

<div class="question-ask">
    <form class="form-horizontal" method="post" action="{% url 'qa:add_question' %}">
        {% csrf_token %}
        <fieldset>
            {% for field in form %}
                <div class="control-group {% if field.errors %}has-error{% endif %}">
                    <label class="control-label">{{ field.label }}</label>
                    <div class="controls">{{ field }}</div>
                </div>
            {% endfor %}
        </fieldset>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary">Добавить</button>
        </div>
    </form>
</div>
{% endblock %}

ask/qa/templates/qa/question_add_comment.html
{% extends "qa/question_details.html" %}

{% block title %}
    {{ block.super }} - Спросить
{% endblock %}


{% block comments %}

{% for e in form.non_field_errors %}
    <div class="alert alert-danger">{{ e }}</div>
{% endfor %}

    {% if user.is_authenticated %}
        <form class="form-horizontal" method="post" action="{% url 'qa:question_details' question.id %}">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    <div class="control-group {% if field.errors %}has-error{% endif %}">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">{{ field }}</div>
                    </div>
                {% endfor %}
            </fieldset>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Добавить комментарий</button>
            </div>
        </form>
    {% else %}
        <p><font color="red">You can't leave comments. Please <a href="{% url 'qa:login' %}">log in</a></font></p>
    {% endif %}

{% endblock %}

ask/qa/templates/qa/question_details.html
{% extends "qa/base.html" %}

{% block title %}
    {{ block.super }} - {{ question.title }}
{% endblock %}

{% block content %}

    <h1>{{ question.title }}</h1>

    <div class="question-details">
        <p>Автор: {{ question.author }}</p>
        <p>Вопрос: {{ question.text }}</p>
        <p>Время: {{ question.added_at }}</p>
        <p>Рейтинг: {{ question.rating }}</p>
    </div>
    <div class="question-likes">
        <p>Понравилось:
        {% for like in question.likes.all %}
            {{ like }},
        {% endfor %}
        </p>
    </div>


    {% if user.is_authenticated %}
        <form class="form-comments" method="post" action="{% url 'qa:question_details' question.id %}">
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                    <div class="control-group {% if field.errors %}has-error{% endif %}">
                        <label class="control-label">{{ field.label }}</label>
                        <div class="controls">{{ field }}</div>
                    </div>
                {% endfor %}
            </fieldset>
            <div class="form-actions">
                <button type="submit" class="btn btn-primary">Добавить комментарий</button>
            </div>
        </form>
    {% else %}
        <p><font color="red">You can't leave comments. Please <a href="{% url 'qa:login' %}">log in</a></font></p>
    {% endif %}

    <div class="question-comments">
        {% for answer in answers %}
            <p>Автор комментария: {{ answer.author }}</p>
            <p>Комментарий: {{ answer.text }}</p>
        {% endfor %}
    </div>


{% endblock %}

ask/qa/templates/qa/questions_main.html
{% extends "qa/base.html" %}

{% block title %}
    {{ block.super }} - главная
{% endblock %}

{% block content %}
    <div class="question-actions">
        <h5>
            <a href="{% url 'qa:popular_questions' %}">Популярные</a>
            <a href="{% url 'qa:new_questions' %}">Новые</a>
            <a href="{% url 'qa:add_question' %}">Задать вопрос</a>
        </h5>
    </div>
    <nav>
        <ul class="paginator">
            {% for question in questions_on_page %}
                <div class="question-header">
                    <div class="question-date">
                        <p>Опубликовано: {{ question.added_at }}</p>
                    </div>
                    <h1><a href="{% url 'qa:question_details' question.id %}">{{ question }}</a></h1>
                    <p>Автор: {{ question.author }}</p>
                    <p>{{ question.text | linebreaksbr | truncatewords:10 }}</p>
                </div>
            {% endfor %}

            <div class="questions-pages">
                {% for p in paginator.page_range %}
                    {% if p == page.number %}
                        <li class="active">page {{ p }}
                    {% else %}

                        {% block pages %}
                        <li><a href="/?page={{ p }}">page {{ p }}</a>
                        {% endblock %}

                    {% endif %}

                        </li>
                {% endfor %}
            </div>

        </ul>
    </nav>
{% endblock %}

ask/qa/templates/qa/questions_new.html
{% extends "qa/questions_main.html" %}

{% block pages %}
<li><a href="{% url 'qa:new_questions' %}?page={{ p }}">page {{ p }}</a>
{% endblock %}

ask/qa/templates/qa/questions_popular.html
{% extends "qa/questions_main.html" %}

{% block pages %}
<li><a href="{% url 'qa:popular_questions' %}?page={{ p }}">page {{ p }}</a>
{% endblock %}

ask/qa/templates/qa/user_login.html
{% extends "qa/base.html" %}

{% block content %}

    {% if error %}
        <div class="alert alert-danger">
            <font color="red">Your username and password didn't match. Please try again.</font>
        </div>
    {% endif %}

    <form method="post" action="{% url 'qa:login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>

{% endblock %}

ask/qa/templates/qa/user_new.html
{% extends "qa/base.html" %}

{% block content %}

    {% if errors %}
        <div class="alert alert-danger">
            <font color="red">
                {% for error in errors %}
                    {{ error }}
                {% endfor %}
            </font>
        </div>
    {% endif %}

    <form method="post" action="{% url 'qa:signup' %}">
    {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.email.label_tag }}</td>
                <td>{{ form.email }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="create" />
    </form>

{% endblock %}